### ISSUE TITLE
Request: 'All' function in Remove Quarantine

### ISSUE THREAD

**Issue by NikoMuffin** [vitorgalvao/remove-quarantine-workflow#1]
### Workflow version

Latest

### Alfred version

Latest

### macOS version

Latest

### Debugger output

```alfred_debugger
N/A
```

### More details

Apologize for using bug report, but there was no way to request a feature.

@vitorgalvao  Is there any chance (pretty please with 🍒 on top) you could add a function to include all quarantined apps in the remove-quarantine workflow?  I realize one can use the Alfred buffer function but it would be so much more helpful and user-friendly to have a function to be able to dequarantine all of the apps in the list of quarantined apps without having to buffer each one and then apply actions to all.

I really hope you consider this as the extension would be perfection. Thank you for considering! Love your extensions. Appreciate your dedication to us in the  Alfred community.

**Comment by vitorgalvao** [comment]
Thank you for the kind words and the request, but this is not something I intend to add. Having to remove quarantine from multiple apps at once is a rare occurrence and is still quite fast to do via the File Buffer (hold <kbd>⌥</kbd><kbd>↓</kbd>). On the other hand, an option to remove from all could be triggered by mistake, which is a potentially undesirable outcome and is not easily reversible. The workflow *allows* you to remove quarantine, it does not encourage it. Quarantining is a security feature and thus should only be disabled on a case-by-case basis when necessary, not as a broad command.

**Comment by NikoMuffin** [comment]
That is very fair vitor. Thank you for taking the time to comment and explain.
