### ISSUE TITLE
Request: Remove quarantine attribute for desktop apps

### ISSUE THREAD

**Issue by NikoMuffin** [vitorgalvao/remove-quarantine-workflow#2]
<img width="531" alt="image" src="https://github.com/vitorgalvao/remove-quarantine-workflow/assets/1836362/7584040b-3134-4c11-b351-3a080ba82eb0">

Hi vitor,
Inspecting the code of your "Remove Quarantine" workflow, is it possible to have Alfred remove quarantine from apps not found in the /Applications/ folder?  The part that needs modification is the code "for app in /Applications/*; do"  I tried to edit it "for app in *; do" but that doesn't work.   If it's not technically possible to do it anywhere, how about applications *and* desktop?  (/Users/macuser/Desktop/App.app)

The request is NOT to add this as a default workflow but I really want to modify mine.

Thanks again for this beautiful workflow. <3

```
app_list=()

for app in /Applications/*; do
  if xattr -p 'com.apple.quarantine' "${app}" &> /dev/null; then
    app_list+=("${app}")
  fi
done

if [[ "${#app_list[@]}" -eq 0 ]]; then
  echo "<?xml version='1.0'?><items>
    <item valid='no'>
    <title>You have no quarantined applications at the root of /Applications</title>
    <subtitle>Use this workflow’s File Action if you need more granularity</subtitle>
    </item>
  </items>"
else
  echo "<?xml version='1.0'?><items>"
  for app in "${app_list[@]}"; do
  	echo "<item arg='${app}' type='file:skipcheck' valid='yes'>"
  	echo "<title>$(basename "${app}")</title>"
  	echo "<icon type='fileicon'>${app}</icon>"
  	echo "</item>"
  done
  echo "</items>"
fi
```

**Comment by vitorgalvao** [comment]
That part of the code is only for *listing* apps in `/Applications`. You can remove quarantine from apps anywhere with the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/). The workflow instructions cover this as the main method.

**Comment by NikoMuffin** [comment]
@vitorgalvao  but this method will not _list_ the apps that need quarantine removed right?  That's kind of a general need I have :( 

Is there any way to list all apps located on the hard drive or at least on the desktop?

**Comment by vitorgalvao** [comment]
Just released a new version that amongst other changes will find apps in more locations.

**Comment by NikoMuffin** [comment]
> Just released a new version that amongst other changes will find apps in more locations.

Vitor, you are a god amongst gods. This works flawlessly now and has improved my workflow so much. Thank you so much! 💝💝💝
