### ISSUE TITLE
Ability to limit scanning to specific folders

### ISSUE THREAD

**Issue by gingerbeardman** [vitorgalvao/remove-quarantine-workflow#3]
### Feature details

With 2023.2 this now scans my whole drive, this resulted in dozens and dozens of quarantined files all over my drive, with each scan/results taking ~6 seconds. I generally only want to remove quarantine from files in /Applications.

So I'd like to request the ability to limit to a particular folder (and its subfolders).

Thanks

**Comment by vitorgalvao** [comment]
Added in 2023.3 (it was done between your request in the forum and opening this issue). Please do let me know if you find any issue. It is a configuration in the workflow and is off by default to keep the same behaviour, so you’ll have to turn it on.
